// Code generated by MockGen. DO NOT EDIT.
// Source: ../../awsclient/awsclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	client "github.com/aws/aws-sdk-go/aws/client"
	gomock "github.com/golang/mock/gomock"
)

// MockAwsClientInterface is a mock of AwsClientInterface interface.
type MockAwsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAwsClientInterfaceMockRecorder
}

// MockAwsClientInterfaceMockRecorder is the mock recorder for MockAwsClientInterface.
type MockAwsClientInterfaceMockRecorder struct {
	mock *MockAwsClientInterface
}

// NewMockAwsClientInterface creates a new mock instance.
func NewMockAwsClientInterface(ctrl *gomock.Controller) *MockAwsClientInterface {
	mock := &MockAwsClientInterface{ctrl: ctrl}
	mock.recorder = &MockAwsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAwsClientInterface) EXPECT() *MockAwsClientInterfaceMockRecorder {
	return m.recorder
}

// GetAWSClientSession mocks base method.
func (m *MockAwsClientInterface) GetAWSClientSession(awsRoleARN, region string) (client.ConfigProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAWSClientSession", awsRoleARN, region)
	ret0, _ := ret[0].(client.ConfigProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAWSClientSession indicates an expected call of GetAWSClientSession.
func (mr *MockAwsClientInterfaceMockRecorder) GetAWSClientSession(awsRoleARN, region interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAWSClientSession", reflect.TypeOf((*MockAwsClientInterface)(nil).GetAWSClientSession), awsRoleARN, region)
}
